language: python
python:
- 3.8
cache: pip
script:
- sh publish.sh
before_install:
- npm install npm@latest -g
before_deploy:
- pip3 install bumpversion
- pip3 install -U python-dotenv
- sudo apt-get update
- nvm install 12
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github
deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    python: 3.8
    branch: master
- provider: pypi
  user: gauragos
  password: '!12345GauravUl#'
  repository: https://upload.pypi.org/legacy
  skip_cleanup: true
  on:
    python: 3.8
    tags: false
