language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
cache: pip
script:
- sh publish.sh
before_deploy:
- pip3 install bumpversion
deploy:
- provider: pypi
  user: gauragos
  password: '!12345GauravUl#'
  repository: https://upload.pypi.org/legacy
  skip_cleanup: true
  on:
    python: 3.8
    tags: true